## Numpy Practical 1
#### Name : Khushi Devidas Helange
#### Roll no.133    Class : TY-A   

In [1]:
import numpy as np

In [66]:
nplist1 = [0,1,2,3,4]

In [67]:
list1 = np.array(nplist1)

In [68]:
nplist2 = [2,3,4,5,5]

In [69]:
list2 = np.array(nplist2)

In [70]:
list1>list2

array([False, False, False, False, False])

In [71]:
list2>list1

array([ True,  True,  True,  True,  True])

In [72]:
list1 != list2

array([ True,  True,  True,  True,  True])

In [73]:
list1>=list2

array([False, False, False, False, False])

In [74]:
list1<=list2

array([ True,  True,  True,  True,  True])

###  Create and numpy array and determine the size occupied by array in memory

In [75]:
from sys import getsizeof

In [76]:
arr1d = np.array(list1)

In [77]:
getsizeof(arr1d) #size in bytes

136

In [78]:
np.sum(arr1d)

10

### Compute sum of all elements across each row and each column of np array

In [79]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
arr2d = np.array(list2)

In [80]:
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [122]:
np.sum(arr2d)

2.0

In [124]:
np.sum(arr2d,axis=0)

2.0

In [82]:
arr2d.dtype

dtype('int64')

In [83]:
arr2d = np.array(list2,dtype= 'float')

In [84]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [85]:
arr2d = arr2d.astype('int')

In [86]:
arr2d = arr2d.astype('str')

In [87]:
arr2d

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U21')

In [88]:
list1

array([0, 1, 2, 3, 4])

In [89]:
np2list = arr2d.tolist()

In [90]:
np2list

[['1', '1', '1'], ['2', '2', '2'], ['3', '3', '3']]

### Calculate Mean Across Dimension of numpy array 

In [91]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [92]:
arr2d = arr2d.astype('float')

In [93]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [94]:
print('Shape:',arr2d.shape) #this print is used in python3 

Shape: (3, 3)


In [95]:
arr2d.dtype


dtype('float64')

In [96]:
arr2d.size

9

In [97]:
arr2d.ndim

2

In [98]:
arr2d.ndim

2

In [99]:
arr1d.ndim

1

In [100]:
arr1d

array([0, 1, 2, 3, 4])

In [101]:
arr1d[1]

1

In [102]:
arr2d.ndim

2

In [103]:
arr1d.ndim

1

In [104]:
type(arr2d)

numpy.ndarray

In [105]:
arr2d = np.mean(arr2d)

In [106]:
arr2d

2.0

In [107]:
arr2d = np.median(arr2d)

In [108]:
arr2d

2.0

In [109]:
arr2d.min()

2.0

In [110]:
arr1d.min()

0

Statistical Operation 

In [111]:
list3 = [[1,2,3,4],[5,6,7,8],[7,8,4,3]]
arr3d = np.array(list3)

In [112]:
arr3d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 4, 3]])

In [113]:
arr3d.min()

1

In [114]:
arr3d.max()

8

In [115]:
arr3d.squeeze()

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 4, 3]])

In [116]:
arr = arr3d[:2,:2]

In [117]:
arr

array([[1, 2],
       [5, 6]])

In [118]:
arr3d.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 4, 3]])